# Generated by Django 5.0.7 on 2024-08-23 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantidade do produto no carrinho."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_categoria",
                    models.CharField(
                        help_text="Nome da categoria, por exemplo, 'Chocolate', 'Baunilha'.",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CupcakesSistem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(max_length=100, verbose_name="Nome do Sistema"),
                ),
                ("version", models.CharField(max_length=10, verbose_name="Versão")),
                (
                    "sobre",
                    models.TextField(blank=True, null=True, verbose_name="Sobre Nós"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("launch_date", models.DateField(verbose_name="Data de Lançamento")),
                (
                    "developer",
                    models.CharField(max_length=100, verbose_name="Desenvolvedor"),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email de Suporte",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "last_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "instagram_link",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "twitter_link",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Endereço"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sistema de Cupcakes",
                "verbose_name_plural": "Sistemas de Cupcakes",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Afghanistan", "Afghanistan"),
                            ("Albania", "Albania"),
                            ("Algeria", "Algeria"),
                            ("American Samoa", "American Samoa"),
                            ("Andorra", "Andorra"),
                            ("Angola", "Angola"),
                            ("Anguilla", "Anguilla"),
                            ("Antarctica", "Antarctica"),
                            ("Antigua and Barbuda", "Antigua and Barbuda"),
                            ("Argentina", "Argentina"),
                            ("Armenia", "Armenia"),
                            ("Aruba", "Aruba"),
                            ("Australia", "Australia"),
                            ("Austria", "Austria"),
                            ("Azerbaijan", "Azerbaijan"),
                            ("Bahamas", "Bahamas"),
                            ("Bahrain", "Bahrain"),
                            ("Bangladesh", "Bangladesh"),
                            ("Barbados", "Barbados"),
                            ("Belarus", "Belarus"),
                            ("Belgium", "Belgium"),
                            ("Belize", "Belize"),
                            ("Benin", "Benin"),
                            ("Bermuda", "Bermuda"),
                            ("Bhutan", "Bhutan"),
                            ("Bolivia", "Bolivia"),
                            ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
                            ("Botswana", "Botswana"),
                            ("Bouvet Island", "Bouvet Island"),
                            ("Brazil", "Brazil"),
                            (
                                "British Indian Ocean Territory",
                                "British Indian Ocean Territory",
                            ),
                            ("British Virgin Islands", "British Virgin Islands"),
                            ("Brunei", "Brunei"),
                            ("Bulgaria", "Bulgaria"),
                            ("Burkina Faso", "Burkina Faso"),
                            ("Burundi", "Burundi"),
                            ("Cambodia", "Cambodia"),
                            ("Cameroon", "Cameroon"),
                            ("Canada", "Canada"),
                            ("Cape Verde", "Cape Verde"),
                            ("Caribbean Netherlands", "Caribbean Netherlands"),
                            ("Cayman Islands", "Cayman Islands"),
                            ("Central African Republic", "Central African Republic"),
                            ("Chad", "Chad"),
                            ("Chile", "Chile"),
                            ("China", "China"),
                            ("Christmas Island", "Christmas Island"),
                            ("Cocos (Keeling) Islands", "Cocos (Keeling) Islands"),
                            ("Colombia", "Colombia"),
                            ("Comoros", "Comoros"),
                            ("Cook Islands", "Cook Islands"),
                            ("Costa Rica", "Costa Rica"),
                            ("Croatia", "Croatia"),
                            ("Cuba", "Cuba"),
                            ("Cura�ao", "Cura�ao"),
                            ("Cyprus", "Cyprus"),
                            ("Czechia", "Czechia"),
                            ("DR Congo", "DR Congo"),
                            ("Denmark", "Denmark"),
                            ("Djibouti", "Djibouti"),
                            ("Dominica", "Dominica"),
                            ("Dominican Republic", "Dominican Republic"),
                            ("Ecuador", "Ecuador"),
                            ("Egypt", "Egypt"),
                            ("El Salvador", "El Salvador"),
                            ("Equatorial Guinea", "Equatorial Guinea"),
                            ("Eritrea", "Eritrea"),
                            ("Estonia", "Estonia"),
                            ("Eswatini", "Eswatini"),
                            ("Ethiopia", "Ethiopia"),
                            ("Falkland Islands", "Falkland Islands"),
                            ("Faroe Islands", "Faroe Islands"),
                            ("Fiji", "Fiji"),
                            ("Finland", "Finland"),
                            ("France", "France"),
                            ("French Guiana", "French Guiana"),
                            ("French Polynesia", "French Polynesia"),
                            (
                                "French Southern and Antarctic Lands",
                                "French Southern and Antarctic Lands",
                            ),
                            ("Gabon", "Gabon"),
                            ("Gambia", "Gambia"),
                            ("Georgia", "Georgia"),
                            ("Germany", "Germany"),
                            ("Ghana", "Ghana"),
                            ("Gibraltar", "Gibraltar"),
                            ("Greece", "Greece"),
                            ("Greenland", "Greenland"),
                            ("Grenada", "Grenada"),
                            ("Guadeloupe", "Guadeloupe"),
                            ("Guam", "Guam"),
                            ("Guatemala", "Guatemala"),
                            ("Guernsey", "Guernsey"),
                            ("Guinea", "Guinea"),
                            ("Guinea-Bissau", "Guinea-Bissau"),
                            ("Guyana", "Guyana"),
                            ("Haiti", "Haiti"),
                            (
                                "Heard Island and McDonald Islands",
                                "Heard Island and McDonald Islands",
                            ),
                            ("Honduras", "Honduras"),
                            ("Hong Kong", "Hong Kong"),
                            ("Hungary", "Hungary"),
                            ("Iceland", "Iceland"),
                            ("India", "India"),
                            ("Indonesia", "Indonesia"),
                            ("Iran", "Iran"),
                            ("Iraq", "Iraq"),
                            ("Ireland", "Ireland"),
                            ("Isle of Man", "Isle of Man"),
                            ("Israel", "Israel"),
                            ("Italy", "Italy"),
                            ("Ivory Coast", "Ivory Coast"),
                            ("Jamaica", "Jamaica"),
                            ("Japan", "Japan"),
                            ("Jersey", "Jersey"),
                            ("Jordan", "Jordan"),
                            ("Kazakhstan", "Kazakhstan"),
                            ("Kenya", "Kenya"),
                            ("Kiribati", "Kiribati"),
                            ("Kosovo", "Kosovo"),
                            ("Kuwait", "Kuwait"),
                            ("Kyrgyzstan", "Kyrgyzstan"),
                            ("Laos", "Laos"),
                            ("Latvia", "Latvia"),
                            ("Lebanon", "Lebanon"),
                            ("Lesotho", "Lesotho"),
                            ("Liberia", "Liberia"),
                            ("Libya", "Libya"),
                            ("Liechtenstein", "Liechtenstein"),
                            ("Lithuania", "Lithuania"),
                            ("Luxembourg", "Luxembourg"),
                            ("Macau", "Macau"),
                            ("Madagascar", "Madagascar"),
                            ("Malawi", "Malawi"),
                            ("Malaysia", "Malaysia"),
                            ("Maldives", "Maldives"),
                            ("Mali", "Mali"),
                            ("Malta", "Malta"),
                            ("Marshall Islands", "Marshall Islands"),
                            ("Martinique", "Martinique"),
                            ("Mauritania", "Mauritania"),
                            ("Mauritius", "Mauritius"),
                            ("Mayotte", "Mayotte"),
                            ("Mexico", "Mexico"),
                            ("Micronesia", "Micronesia"),
                            ("Moldova", "Moldova"),
                            ("Monaco", "Monaco"),
                            ("Mongolia", "Mongolia"),
                            ("Montenegro", "Montenegro"),
                            ("Montserrat", "Montserrat"),
                            ("Morocco", "Morocco"),
                            ("Mozambique", "Mozambique"),
                            ("Myanmar", "Myanmar"),
                            ("Namibia", "Namibia"),
                            ("Nauru", "Nauru"),
                            ("Nepal", "Nepal"),
                            ("Netherlands", "Netherlands"),
                            ("New Caledonia", "New Caledonia"),
                            ("New Zealand", "New Zealand"),
                            ("Nicaragua", "Nicaragua"),
                            ("Niger", "Niger"),
                            ("Nigeria", "Nigeria"),
                            ("Niue", "Niue"),
                            ("Norfolk Island", "Norfolk Island"),
                            ("North Korea", "North Korea"),
                            ("North Macedonia", "North Macedonia"),
                            ("Northern Mariana Islands", "Northern Mariana Islands"),
                            ("Norway", "Norway"),
                            ("Oman", "Oman"),
                            ("Pakistan", "Pakistan"),
                            ("Palau", "Palau"),
                            ("Palestine", "Palestine"),
                            ("Panama", "Panama"),
                            ("Papua New Guinea", "Papua New Guinea"),
                            ("Paraguay", "Paraguay"),
                            ("Peru", "Peru"),
                            ("Philippines", "Philippines"),
                            ("Pitcairn Islands", "Pitcairn Islands"),
                            ("Poland", "Poland"),
                            ("Portugal", "Portugal"),
                            ("Puerto Rico", "Puerto Rico"),
                            ("Qatar", "Qatar"),
                            ("Republic of the Congo", "Republic of the Congo"),
                            ("Romania", "Romania"),
                            ("Russia", "Russia"),
                            ("Rwanda", "Rwanda"),
                            ("R�union", "R�union"),
                            ("Saint Barth�lemy", "Saint Barth�lemy"),
                            (
                                "Saint Helena, Ascension and Tristan da Cunha",
                                "Saint Helena, Ascension and Tristan da Cunha",
                            ),
                            ("Saint Kitts and Nevis", "Saint Kitts and Nevis"),
                            ("Saint Lucia", "Saint Lucia"),
                            ("Saint Martin", "Saint Martin"),
                            ("Saint Pierre and Miquelon", "Saint Pierre and Miquelon"),
                            (
                                "Saint Vincent and the Grenadines",
                                "Saint Vincent and the Grenadines",
                            ),
                            ("Samoa", "Samoa"),
                            ("San Marino", "San Marino"),
                            ("Saudi Arabia", "Saudi Arabia"),
                            ("Senegal", "Senegal"),
                            ("Serbia", "Serbia"),
                            ("Seychelles", "Seychelles"),
                            ("Sierra Leone", "Sierra Leone"),
                            ("Singapore", "Singapore"),
                            ("Sint Maarten", "Sint Maarten"),
                            ("Slovakia", "Slovakia"),
                            ("Slovenia", "Slovenia"),
                            ("Solomon Islands", "Solomon Islands"),
                            ("Somalia", "Somalia"),
                            ("South Africa", "South Africa"),
                            ("South Georgia", "South Georgia"),
                            ("South Korea", "South Korea"),
                            ("South Sudan", "South Sudan"),
                            ("Spain", "Spain"),
                            ("Sri Lanka", "Sri Lanka"),
                            ("Sudan", "Sudan"),
                            ("Suriname", "Suriname"),
                            ("Svalbard and Jan Mayen", "Svalbard and Jan Mayen"),
                            ("Sweden", "Sweden"),
                            ("Switzerland", "Switzerland"),
                            ("Syria", "Syria"),
                            ("S�o Tom� and Pr�ncipe", "S�o Tom� and Pr�ncipe"),
                            ("Taiwan", "Taiwan"),
                            ("Tajikistan", "Tajikistan"),
                            ("Tanzania", "Tanzania"),
                            ("Thailand", "Thailand"),
                            ("Timor-Leste", "Timor-Leste"),
                            ("Togo", "Togo"),
                            ("Tokelau", "Tokelau"),
                            ("Tonga", "Tonga"),
                            ("Trinidad and Tobago", "Trinidad and Tobago"),
                            ("Tunisia", "Tunisia"),
                            ("Turkey", "Turkey"),
                            ("Turkmenistan", "Turkmenistan"),
                            ("Turks and Caicos Islands", "Turks and Caicos Islands"),
                            ("Tuvalu", "Tuvalu"),
                            ("Uganda", "Uganda"),
                            ("Ukraine", "Ukraine"),
                            ("United Arab Emirates", "United Arab Emirates"),
                            ("United Kingdom", "United Kingdom"),
                            ("United States", "United States"),
                            (
                                "United States Minor Outlying Islands",
                                "United States Minor Outlying Islands",
                            ),
                            (
                                "United States Virgin Islands",
                                "United States Virgin Islands",
                            ),
                            ("Uruguay", "Uruguay"),
                            ("Uzbekistan", "Uzbekistan"),
                            ("Vanuatu", "Vanuatu"),
                            ("Vatican City", "Vatican City"),
                            ("Venezuela", "Venezuela"),
                            ("Vietnam", "Vietnam"),
                            ("Wallis and Futuna", "Wallis and Futuna"),
                            ("Western Sahara", "Western Sahara"),
                            ("Yemen", "Yemen"),
                            ("Zambia", "Zambia"),
                            ("Zimbabwe", "Zimbabwe"),
                            ("�land Islands", "�land Islands"),
                        ],
                        default="Brazil",
                        max_length=100,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("street_address", models.CharField(max_length=255)),
                (
                    "apartment_suite",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("order_notes", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Endereço do Usuário",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data em que o carrinho foi criado.",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuário ao qual o carrinho pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "itens",
                    models.ManyToManyField(related_name="carrinho", to="core.cartitem"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Email Address"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Under Review", "Under Review"),
                            ("Resolved", "Resolved"),
                        ],
                        default="Pending",
                        max_length=50,
                        verbose_name="Contact Status",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Is Resolved"),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Response Message"
                    ),
                ),
                (
                    "contact_date",
                    models.DateField(auto_now_add=True, verbose_name="Contact Date"),
                ),
                (
                    "resolved_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resolution Date"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cupcake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Insira o título do cupcake, por exemplo, 'Cupcake de Chocolate'.",
                        max_length=255,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Insira uma descrição detalhada do cupcake, incluindo sabor, textura, etc."
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço original do cupcake (use ponto para separar decimais).",
                        max_digits=10,
                    ),
                ),
                (
                    "sale",
                    models.BooleanField(
                        default=False, help_text="Marque se o cupcake está em promoção."
                    ),
                ),
                (
                    "preco_sale",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço promocional do cupcake (use ponto para separar decimais). Preenchido apenas se o produto estiver em promoção.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "quantidade_disponivel",
                    models.IntegerField(
                        help_text="Número de unidades disponíveis em estoque."
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Código SKU único para o cupcake.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "data_lancamento",
                    models.DateField(help_text="Data de lançamento do cupcake."),
                ),
                (
                    "esta_em_destaque",
                    models.BooleanField(
                        default=False,
                        help_text="Marque se o cupcake deve ser destacado na página inicial.",
                    ),
                ),
                (
                    "ingrediente",
                    models.TextField(
                        help_text="Nome dos ingredientes, por exemplo, 'Açúcar', 'Farinha de Trigo'."
                    ),
                ),
                (
                    "etiqueta",
                    models.CharField(
                        help_text="Nome da etiqueta, por exemplo, 'Vegano', 'Sem Glúten'.",
                        max_length=255,
                    ),
                ),
                (
                    "cobertura",
                    models.CharField(
                        help_text="Nome da cobertura, por exemplo, 'Chocolate', 'Baunilha', 'Morango'.",
                        max_length=255,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        help_text="A categoria associada a este cupcake.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categoria_cupcakes",
                        to="core.categoria",
                    ),
                ),
                (
                    "quem_cadastrou",
                    models.ForeignKey(
                        help_text="Usuário que cadastrou o cupcake.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cupcake",
            field=models.ForeignKey(
                help_text="O cupcake adicionado ao carrinho.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.cupcake",
            ),
        ),
        migrations.CreateModel(
            name="CupcakeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "normal",
                    models.ImageField(
                        help_text="Imagem normal 400 x 400.",
                        upload_to="cupcakes-fotos/",
                    ),
                ),
                (
                    "large_size",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        help_text="Imagem large 600 x 600.",
                        null=True,
                        upload_to="cupcakes-fotos/large-size",
                    ),
                ),
                (
                    "small_size",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        help_text="Imagem small 140 x 140.",
                        null=True,
                        upload_to="cupcakes-fotos/small-size",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição ou legenda da imagem.",
                        null=True,
                    ),
                ),
                ("_processed", models.BooleanField(default=False, editable=False)),
                (
                    "cupcake",
                    models.ForeignKey(
                        help_text="O cupcake ao qual esta imagem está associada.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="core.cupcake",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais", models.CharField(max_length=100)),
                ("primeiro_nome", models.CharField(max_length=100)),
                ("ultimo_nome", models.CharField(max_length=100)),
                (
                    "nome_empresa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("endereco", models.CharField(max_length=255)),
                (
                    "apartamento_sala_unidade",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("criar_conta", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enderecos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_pedido",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data em que o pedido foi realizado.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Processando", "Processando"),
                            ("Enviado", "Enviado"),
                            ("Entregue", "Entregue"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Pendente",
                        help_text="Status do pedido.",
                        max_length=50,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total do pedido.",
                        max_digits=10,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        help_text="Usuário que fez o pedido.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.address",
                    ),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        help_text="Carrinho associado a este pedido.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cart",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuário que fez o pedido.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Aguardando pagamento", "Aguardando pagamento"),
                            ("Pago", "Pago"),
                            ("Falha no pagamento", "Falha no pagamento"),
                        ],
                        default="Aguardando pagamento",
                        help_text="Status do pagamento.",
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cartão de Crédito", "Cartão de Crédito"),
                            ("Boleto", "Boleto"),
                            ("Pix", "Pix"),
                            ("Transferência Bancária", "Transferência Bancária"),
                        ],
                        help_text="Método de pagamento utilizado.",
                        max_length=50,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total do pedido.",
                        max_digits=10,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data em que o checkout foi realizado.",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="ID da transação de pagamento.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Pedido associado a este checkout.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout",
                        to="core.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoliticaEnvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "politica",
                    models.TextField(
                        help_text="Descrição da política de envio para este cupcake."
                    ),
                ),
                (
                    "cupcake",
                    models.ForeignKey(
                        help_text="O cupcake associado a esta política de envio.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="politicas_envio",
                        to="core.cupcake",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="profile_images/default.jpeg",
                        upload_to="profile_images",
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avaliacao",
                    models.IntegerField(
                        help_text="Avaliação dada ao cupcake (de 1 a 5 estrelas)."
                    ),
                ),
                (
                    "comentario",
                    models.TextField(help_text="Comentário sobre o cupcake."),
                ),
                (
                    "data",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que a avaliação foi feita.",
                    ),
                ),
                (
                    "cupcake",
                    models.ForeignKey(
                        help_text="O cupcake que está sendo avaliado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.cupcake",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuário que fez a avaliação.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "unique_together": {("usuario", "cupcake")},
            },
        ),
    ]
