# Generated by Django 5.0.7 on 2024-08-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
