# Generated by Django 5.0.7 on 2024-08-23 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Email Address"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Under Review", "Under Review"),
                            ("Resolved", "Resolved"),
                        ],
                        default="Pending",
                        max_length=50,
                        verbose_name="Contact Status",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Is Resolved"),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Response Message"
                    ),
                ),
                (
                    "contact_date",
                    models.DateField(auto_now_add=True, verbose_name="Contact Date"),
                ),
                (
                    "resolved_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resolution Date"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By",
                    ),
                ),
            ],
        ),
    ]
